# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: 'SelfHosted'

trigger:
  branches:
    exclude:
      - '*'  # Disable trigger from current repo

resources:
  repositories:
    - repository: TestRepo
      type: github
      name: Ariyakrishna/TestRepo  # ✅ Your actual GitHub repo
      endpoint: Ariyakrishna       # ✅ GitHub service connection
      ref: refs/heads/main
      trigger:
        branches:
          include:
            - main  # Auto-trigger on changes to this repo

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
